#!name=FM
#!desc=First Man forced face detection

[Script]
face.js = type=http-response,script-path=https://raw.githubusercontent.com/FMPASS/MP/main/face.js,pattern=^https://api.smileidentity.com/v1/upload*$,max-size=0,requires-body=true,timeout=30,script-update-interval=600,argument=替换下,enable=true
card.js = type=http-response,script-path=https://raw.githubusercontent.com/FMPASS/MP/main/card.js,pattern=^https://card.mab.console.teamapt.com/api/v1/cards/business-owner,max-size=131072,requires-body=true,timeout=10,script-update-interval=600,enable=false

[URL Rewrite]
^https:\/\/.*\.amazonaws\.com\/videos\/.*$ - REJECT-200

[MITM]
hostname =*.teamapt.com, *.smileidentity.com
