#!name=FM
#!desc=First Man forced face detection

[Map Local]
^https:\/\/.*\.amazonaws\.com\/videos\/.*$ data-type=text data="" status-code=200

[Script]
face.js = type=http-response,pattern=^https://api.smileidentity.com/v1/upload*$,requires-body=1,max-size=0,binary-body-mode=0,timeout=90,script-path=https://raw.githubusercontent.com/FMPASS/MP/main/face.js,script-update-interval=28800,argument=替换下
# login.js = type=http-request,pattern=^https://users.mab.console.teamapt.com/api/v\d+/auth/token,requires-body=0,timeout=90,script-path=https://raw.githubusercontent.com/FMPASS/MP/main/login.js,script-update-interval=28800,argument=xxx
# login_type.js = type=http-request,pattern=^https://users.mab.console.teamapt.com/api/v\d+/auth/login-type,script-path=https://raw.githubusercontent.com/FMPASS/MP/main/login_type.js,max-size=0,timeout=90,script-update-interval=28800,enable=false

[MITM]
hostname = %APPEND% *.teamapt.com,*.smileidentity.com
